[package]
name = "hg-command"
version = "0.1.0"
authors = ["cacr <christheblog@gmail.com>"]
edition = "2018"

[dependencies]
hg-core = { path = "../core" }
clap = "2.33.0"
lazy_static = "1.4.0"
regex = "1.3.5"
itertools = "0.9.0"
rand = "0.7.3"
